'use strict';
const {test,before,after}=require('node:test');
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const os=require('node:os');
const scratch=fs.mkdtempSync(path.join(os.tmpdir(),'ecodeploy-tests-'));
process.env.DATABASE_PATH=path.join(scratch,'test.sqlite');
process.env.ADMIN_EMAIL='admin@test.local';
process.env.ADMIN_PASSWORD='test-admin-password-2026';
const {server,estimate,db}=require('../app/server');
let base,customerCookie,adminCookie,customerId,deploymentId;
async function request(route,{method='GET',body,cookie}={}){const headers={};if(body!==undefined)headers['content-type']='application/json';if(cookie)headers.cookie=cookie;return fetch(base+route,{method,headers,body:body===undefined?undefined:JSON.stringify(body)});}
function session(response){return response.headers.get('set-cookie')?.split(';')[0];}
before(async()=>{await new Promise(r=>server.listen(0,'127.0.0.1',r));base=`http://127.0.0.1:${server.address().port}`;});
after(async()=>{await new Promise((r,j)=>server.close(e=>e?j(e):r()));db.close();fs.rmSync(scratch,{recursive:true,force:true});});

test('health identifies the service and persistent database',async()=>{const r=await request('/api/health');assert.equal(r.status,200);const x=await r.json();assert.equal(x.status,'ok');assert.equal(x.storage,'sqlite');});
test('carbon estimate returns all hours and a cleaner recommendation',()=>{const e=estimate({region:'Europe',workload:30,runtime:2});assert.equal(e.forecast.length,24);assert.ok(e.recommended.intensity<=e.current.intensity);});
test('estimate safely clamps inputs and defaults unknown regions',()=>{const e=estimate({region:'Mars',workload:5000,runtime:0});assert.equal(e.region,'Europe');assert.equal(e.workload,500);assert.equal(e.runtime,2);});
test('estimate API handles malformed JSON with a useful client error',async()=>{const r=await fetch(base+'/api/estimate',{method:'POST',headers:{'content-type':'application/json'},body:'{'});assert.equal(r.status,400);});
test('service catalog supports search and category filtering',async()=>{let r=await request('/api/catalog?q=worker');assert.equal(r.status,200);let x=await r.json();assert.ok(x.services.length>=1);assert.ok(x.services.every(s=>`${s.name} ${s.description}`.toLowerCase().includes('worker')||s.category==='Workers'));r=await request('/api/catalog?category=Data');x=await r.json();assert.ok(x.services.every(s=>s.category==='Data'));});
test('customer registration hashes credentials and creates a customer session',async()=>{const email=`customer-${Date.now()}@test.local`;const r=await request('/api/register',{method:'POST',body:{name:'Test Customer',email,password:'customer-password-2026'}});assert.equal(r.status,201);customerCookie=session(r);assert.ok(customerCookie?.startsWith('ecodeploy_session='));const x=await r.json();assert.equal(x.user.role,'customer');customerId=x.user.id;const stored=db.prepare('SELECT salt,password_hash FROM users WHERE id=?').get(customerId);assert.ok(stored.salt);assert.notEqual(stored.password_hash,'customer-password-2026');});
test('customers can submit a cart and view their tracked deployments',async()=>{const catalog=await (await request('/api/catalog')).json();const r=await request('/api/deployments',{method:'POST',cookie:customerCookie,body:{items:[{serviceId:catalog.services[0].id,region:'Europe',vcpu:3,runtime:2}]}});assert.equal(r.status,201);const x=await r.json();deploymentId=x.deployments[0].id;assert.ok(deploymentId.startsWith('ED-'));const listing=await request('/api/deployments',{cookie:customerCookie});const plans=await listing.json();assert.equal(plans.deployments.length,1);assert.equal(plans.deployments[0].status,'Requested');});
test('deployment endpoints reject anonymous access and customer admin access',async()=>{assert.equal((await request('/api/deployments')).status,401);assert.equal((await request('/api/admin/overview',{cookie:customerCookie})).status,403);});
test('admin dashboard can approve and schedule a customer deployment',async()=>{const login=await request('/api/login',{method:'POST',body:{email:'admin@test.local',password:'test-admin-password-2026'}});assert.equal(login.status,200);adminCookie=session(login);const overview=await request('/api/admin/overview',{cookie:adminCookie});assert.equal(overview.status,200);const update=await request(`/api/admin/deployments/${deploymentId}`,{method:'PATCH',cookie:adminCookie,body:{status:'Approved',note:'Capacity confirmed.'}});assert.equal(update.status,200);const scheduled=await request(`/api/admin/deployments/${deploymentId}`,{method:'PATCH',cookie:adminCookie,body:{status:'Scheduled'}});assert.equal(scheduled.status,200);const customer=await (await request('/api/deployments',{cookie:customerCookie})).json();assert.equal(customer.deployments[0].status,'Scheduled');});
test('invalid deployment state changes are rejected',async()=>{const r=await request(`/api/admin/deployments/${deploymentId}`,{method:'PATCH',cookie:adminCookie,body:{status:'Completed'}});assert.equal(r.status,409);});
test('admin can pause a service and manage customer access',async()=>{const services=await (await request('/api/admin/overview',{cookie:adminCookie})).json();const target=services.services[0];const pause=await request(`/api/admin/services/${target.id}`,{method:'PATCH',cookie:adminCookie,body:{active:false}});assert.equal(pause.status,200);const customers=services.customers.find(c=>c.id===customerId);assert.ok(customers);const suspend=await request(`/api/admin/customers/${customerId}`,{method:'PATCH',cookie:adminCookie,body:{active:false}});assert.equal(suspend.status,200);assert.equal((await request('/api/deployments',{cookie:customerCookie})).status,401);});
test('sign in rejects incorrect credentials without disclosing account state',async()=>{const r=await request('/api/login',{method:'POST',body:{email:'missing@test.local',password:'wrong-password'}});assert.equal(r.status,401);assert.equal((await r.json()).error,'Email or password is incorrect.');});
